"use client" 

import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import {Toaster } from "react-hot-toast";
import {createContext, useState} from "react"

const inter = Inter({ subsets: ["latin"] });

export const server = "https://nodejs-todoapp-0k1g.onrender.com/api/v1";

export const Context = createContext({isAuthenticated: false});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }) {
  const [isAuthenticated, setIsAuthenticated] = useState(false)
  const [loading, setLoading] = useState(false)
  const [user, setUser] = useState({})

  return (
    <html lang="en">
      <body className={inter.className}>
      <Context.Provider value = {{isAuthenticated,setIsAuthenticated,loading,setLoading,user,setUser}}>
        <Header/>
        { children }
        <Toaster/>     
      </Context.Provider> 
      </body>
    </html>
  );
}
